
package publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param fileData
     * @param fileName
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/postFileRequest", output = "http://publicar/WebServices/postFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicar/WebServices/postFile/Fault/IOException")
    })
    public boolean postFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName,
        @WebParam(name = "fileData", partName = "fileData")
        byte[] fileData)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/altaCiudadRequest", output = "http://publicar/WebServices/altaCiudadResponse")
    public boolean altaCiudad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataRuta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarDatosRutaRequest", output = "http://publicar/WebServices/listarDatosRutaResponse")
    public DataRuta listarDatosRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/ingresarNombreRequest", output = "http://publicar/WebServices/ingresarNombreResponse")
    public boolean ingresarNombre(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg12
     * @param arg13
     * @param arg14
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/altaRutaVueloRequest", output = "http://publicar/WebServices/altaRutaVueloResponse")
    public int altaRutaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        float arg4,
        @WebParam(name = "arg5", partName = "arg5")
        float arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        DataColeccion arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        String arg12,
        @WebParam(name = "arg13", partName = "arg13")
        EstadoRuta arg13,
	    @WebParam(name = "arg14", partName = "arg14")
	    String arg14);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataCiudad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarDatosCiudadRequest", output = "http://publicar/WebServices/listarDatosCiudadResponse")
    public DataCiudad listarDatosCiudad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/vuelosDeRutaRequest", output = "http://publicar/WebServices/vuelosDeRutaResponse")
    public DataColeccion vuelosDeRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getResultadoBusquedaRutasRequest", output = "http://publicar/WebServices/getResultadoBusquedaRutasResponse")
    public DataColeccion getResultadoBusquedaRutas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getResultadoBusquedaPaquetesRequest", output = "http://publicar/WebServices/getResultadoBusquedaPaquetesResponse")
    public DataColeccion getResultadoBusquedaPaquetes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/agregarRutaPaqueteRequest", output = "http://publicar/WebServices/agregarRutaPaqueteResponse")
    public boolean agregarRutaPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        Asiento arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataCiudad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getOrigenRutaRequest", output = "http://publicar/WebServices/getOrigenRutaResponse")
    public DataCiudad getOrigenRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataCiudad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getDestinoRutaRequest", output = "http://publicar/WebServices/getDestinoRutaResponse")
    public DataCiudad getDestinoRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/confirmarRutaRequest", output = "http://publicar/WebServices/confirmarRutaResponse")
    public void confirmarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/rechazarRutaRequest", output = "http://publicar/WebServices/rechazarRutaResponse")
    public void rechazarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/visitarRutaRequest", output = "http://publicar/WebServices/visitarRutaResponse")
    public void visitarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);
    
    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/finalizarRutaRequest", output = "http://publicar/WebServices/finalizarRutaResponse")
    public void finalizarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/existeRutaRequest", output = "http://publicar/WebServices/existeRutaResponse")
    public boolean existeRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/nicknameAerolineaDeRutaRequest", output = "http://publicar/WebServices/nicknameAerolineaDeRutaResponse")
    public String nicknameAerolineaDeRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/nombreCiudadOrigenRutaRequest", output = "http://publicar/WebServices/nombreCiudadOrigenRutaResponse")
    public String nombreCiudadOrigenRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/nombreCiudadDestinoRutaRequest", output = "http://publicar/WebServices/nombreCiudadDestinoRutaResponse")
    public String nombreCiudadDestinoRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosPaquetesRutasRequest", output = "http://publicar/WebServices/leerDatosPaquetesRutasResponse")
    public void leerDatosPaquetesRutas();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosRutasVueloRequest", output = "http://publicar/WebServices/leerDatosRutasVueloResponse")
    public void leerDatosRutasVuelo();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosCiudadesRequest", output = "http://publicar/WebServices/leerDatosCiudadesResponse")
    public void leerDatosCiudades();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosCategoriasRequest", output = "http://publicar/WebServices/leerDatosCategoriasResponse")
    public void leerDatosCategorias();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarRutasRequest", output = "http://publicar/WebServices/listarRutasResponse")
    public DataColeccion listarRutas();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarRutasConfirmadasRequest", output = "http://publicar/WebServices/listarRutasConfirmadasResponse")
    public DataColeccion listarRutasConfirmadas();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/categoriasConRutasRequest", output = "http://publicar/WebServices/categoriasConRutasResponse")
    public DataColeccion categoriasConRutas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/crearClienteRequest", output = "http://publicar/WebServices/crearClienteResponse")
    public int crearCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        Documento arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/crearAerolineaRequest", output = "http://publicar/WebServices/crearAerolineaResponse")
    public int crearAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/existeUsuarioRequest", output = "http://publicar/WebServices/existeUsuarioResponse")
    public boolean existeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarUsuariosRequest", output = "http://publicar/WebServices/listarUsuariosResponse")
    public DataColeccion listarUsuarios();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/seguidosDeUsuarioRequest", output = "http://publicar/WebServices/seguidosDeUsuarioResponse")
    public DataColeccion seguidosDeUsuario(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);
    
    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/seguidoresDeUsuarioRequest", output = "http://publicar/WebServices/seguidoresDeUsuarioResponse")
    public DataColeccion seguidoresDeUsuario(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarDatosUsuarioNicknameRequest", output = "http://publicar/WebServices/listarDatosUsuarioNicknameResponse")
    public DataUsuario listarDatosUsuarioNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarReservasUsuarioRequest", output = "http://publicar/WebServices/listarReservasUsuarioResponse")
    public DataColeccion listarReservasUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/nombresReservasUsuarioRequest", output = "http://publicar/WebServices/nombresReservasUsuarioResponse")
    public DataColeccion nombresReservasUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarPaquetesUsuarioRequest", output = "http://publicar/WebServices/listarPaquetesUsuarioResponse")
    public DataColeccion listarPaquetesUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/setDatosAerolineaRequest", output = "http://publicar/WebServices/setDatosAerolineaResponse")
    public void setDatosAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarAerolineasConRutasRequest", output = "http://publicar/WebServices/listarAerolineasConRutasResponse")
    public DataColeccion listarAerolineasConRutas();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarRutasDeAerolineaRequest", output = "http://publicar/WebServices/listarRutasDeAerolineaResponse")
    public DataColeccion listarRutasDeAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/infoRutasDeAerolineaRequest", output = "http://publicar/WebServices/infoRutasDeAerolineaResponse")
    public DataColeccion infoRutasDeAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/setDatosClienteRequest", output = "http://publicar/WebServices/setDatosClienteResponse")
    public void setDatosCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/esClienteRequest", output = "http://publicar/WebServices/esClienteResponse")
    public boolean esCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns publicar.DataSesion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/loginUsuarioRequest", output = "http://publicar/WebServices/loginUsuarioResponse")
    public DataSesion loginUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        boolean arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarVuelosAerolineaRequest", output = "http://publicar/WebServices/listarVuelosAerolineaResponse")
    public DataColeccion listarVuelosAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/setImagenAndPasswordUsuarioRequest", output = "http://publicar/WebServices/setImagenAndPasswordUsuarioResponse")
    public void setImagenAndPasswordUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/paquetesCanjeablesRequest", output = "http://publicar/WebServices/paquetesCanjeablesResponse")
    public DataColeccion paquetesCanjeables(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/reservasSinCheckInRequest", output = "http://publicar/WebServices/reservasSinCheckInResponse")
    public DataColeccion reservasSinCheckIn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns publicar.DataClienteVuelo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/verReservaRequest", output = "http://publicar/WebServices/verReservaResponse")
    public DataClienteVuelo verReserva(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/realizarCheckInRequest", output = "http://publicar/WebServices/realizarCheckInResponse")
    public boolean realizarCheckIn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/reservasConCheckInRequest", output = "http://publicar/WebServices/reservasConCheckInResponse")
    public DataColeccion reservasConCheckIn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns publicar.DataCheckIn
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/consultaCheckInRequest", output = "http://publicar/WebServices/consultaCheckInResponse")
    public DataCheckIn consultaCheckIn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/seguirUsuarioRequest", output = "http://publicar/WebServices/seguirUsuarioResponse")
    public int seguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/dejarDeSeguirUsuarioRequest", output = "http://publicar/WebServices/dejarDeSeguirUsuarioResponse")
    public int dejarDeSeguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/esSeguidorRequest", output = "http://publicar/WebServices/esSeguidorResponse")
    public boolean esSeguidor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosUsuariosRequest", output = "http://publicar/WebServices/leerDatosUsuariosResponse")
    public void leerDatosUsuarios();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/altaVueloRequest", output = "http://publicar/WebServices/altaVueloResponse")
    public boolean altaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataVuelo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarDatosVueloRequest", output = "http://publicar/WebServices/listarDatosVueloResponse")
    public DataVuelo listarDatosVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/reservaDeVueloRequest", output = "http://publicar/WebServices/reservaDeVueloResponse")
    public int reservaDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        Asiento arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        DataColeccion arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarReservasAsociadasVueloRequest", output = "http://publicar/WebServices/listarReservasAsociadasVueloResponse")
    public DataColeccion listarReservasAsociadasVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.ParPaqueteRutas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/mostrarInfoPaqueteRequest", output = "http://publicar/WebServices/mostrarInfoPaqueteResponse")
    public ParPaqueteRutas mostrarInfoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/crearPaqueteRequest", output = "http://publicar/WebServices/crearPaqueteResponse")
    public boolean crearPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        float arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarPaquetesConRutasRequest", output = "http://publicar/WebServices/listarPaquetesConRutasResponse")
    public DataColeccion listarPaquetesConRutas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/comprarPaqueteRequest", output = "http://publicar/WebServices/comprarPaqueteResponse")
    public boolean comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        float arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getCostoPaqueteRequest", output = "http://publicar/WebServices/getCostoPaqueteResponse")
    public float getCostoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/calcularVencimientoCompraRequest", output = "http://publicar/WebServices/calcularVencimientoCompraResponse")
    public String calcularVencimientoCompra(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getDataPaqueteRequest", output = "http://publicar/WebServices/getDataPaqueteResponse")
    public DataPaquete getDataPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getDataPaqueteRutaRequest", output = "http://publicar/WebServices/getDataPaqueteRutaResponse")
    public DataColeccion getDataPaqueteRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarDataPaquetesRequest", output = "http://publicar/WebServices/listarDataPaquetesResponse")
    public DataColeccion listarDataPaquetes();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/yaComproPaqueteRequest", output = "http://publicar/WebServices/yaComproPaqueteResponse")
    public boolean yaComproPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/paqueteContieneRutasRequest", output = "http://publicar/WebServices/paqueteContieneRutasResponse")
    public boolean paqueteContieneRutas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/paqueteContieneARutaRequest", output = "http://publicar/WebServices/paqueteContieneARutaResponse")
    public boolean paqueteContieneARuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/reservaDeVueloPaqueteRequest", output = "http://publicar/WebServices/reservaDeVueloPaqueteResponse")
    public int reservaDeVueloPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        Asiento arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        DataColeccion arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosReservasRequest", output = "http://publicar/WebServices/leerDatosReservasResponse")
    public void leerDatosReservas();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosPaquetesRequest", output = "http://publicar/WebServices/leerDatosPaquetesResponse")
    public void leerDatosPaquetes();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosVueloRequest", output = "http://publicar/WebServices/leerDatosVueloResponse")
    public void leerDatosVuelo();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/leerDatosCompraPaquetesRequest", output = "http://publicar/WebServices/leerDatosCompraPaquetesResponse")
    public void leerDatosCompraPaquetes();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/nombreAerolineaDeRutaRequest", output = "http://publicar/WebServices/nombreAerolineaDeRutaResponse")
    public String nombreAerolineaDeRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarPaquetesNoCompradosRequest", output = "http://publicar/WebServices/listarPaquetesNoCompradosResponse")
    public DataColeccion listarPaquetesNoComprados();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarClientesRequest", output = "http://publicar/WebServices/listarClientesResponse")
    public DataColeccion listarClientes();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listasPaquetesRegistradosRequest", output = "http://publicar/WebServices/listasPaquetesRegistradosResponse")
    public DataColeccion listasPaquetesRegistrados();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarCategoriasRequest", output = "http://publicar/WebServices/listarCategoriasResponse")
    public DataColeccion listarCategorias();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarAerolineasRequest", output = "http://publicar/WebServices/listarAerolineasResponse")
    public DataColeccion listarAerolineas();

    /**
     * 
     * @return
     *     returns publicar.DataColeccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/listarCiudadesRequest", output = "http://publicar/WebServices/listarCiudadesResponse")
    public DataColeccion listarCiudades();

    /**
     * 
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/getFileRequest", output = "http://publicar/WebServices/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicar/WebServices/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName)
        throws IOException_Exception
    ;

}
